### ISSUE TITLE
Set default value to Infinity

### ISSUE THREAD

**Issue by Baggz** [apiaryio/drafter#251] opened 2016-03-21 19:00 UTC
Hello,

I'm trying to set default value to Infinity...

```
* maxInheritanceDepth: 3 (number)
    * Default: Infinity
```

...but the Refract I'm getting is the following.

```
{
  "element":"member",
  "content":{
    "key":{
      "element":"string",
      "content":"maxInheritanceDepth"
    },
    "value":{
      "element":"number",
      "attributes":{
        "default":null
      },
      "content":3
    }
  }
}
```

You can see that `default` is set to `null`.

Is that an intended behaviour?

Thanks for the clarification!

**Comment by kylef** [comment] 2016-03-21 19:56
I wasn't aware this was possible and it's not mentioned in the spec. However, I've tested this with the latest version of Drafter and it is exposing Infinity in both YAML and JSON outputs.

Here's a minimal blueprint to produce:

#### `blueprint.apib`

```apib
# API
## Data Structures
### Example

+ maxInheritnceDepth: 3 (number)
    * Default: Infinity
```

#### `$ drafter  blueprint.apib`

```yaml
element: "parseResult"
content:
  -
    element: "category"
    meta:
      classes:
        - "api"
      title: "API"
    content:
      -
        element: "category"
        meta:
          classes:
            - "dataStructures"
        content:
          -
            element: "dataStructure"
            content:
              -
                element: "object"
                meta:
                  id: "Example"
                content:
                  -
                    element: "member"
                    content:
                      key:
                        element: "string"
                        content: "maxInheritnceDepth"
                      value:
                        element: "number"
                        attributes:
                          default: inf
                        content: 3
```

#### `$ drafter  blueprint.apib -f json`

```json
{
  "element": "parseResult",
  "content": [
    {
      "element": "category",
      "meta": {
        "classes": [
          "api"
        ],
        "title": "API"
      },
      "content": [
        {
          "element": "category",
          "meta": {
            "classes": [
              "dataStructures"
            ]
          },
          "content": [
            {
              "element": "dataStructure",
              "content": [
                {
                  "element": "object",
                  "meta": {
                    "id": "Example"
                  },
                  "content": [
                    {
                      "element": "member",
                      "content": {
                        "key": {
                          "element": "string",
                          "content": "maxInheritnceDepth"
                        },
                        "value": {
                          "element": "number",
                          "attributes": {
                            "default": inf
                          },
                          "content": 3
                        }
                      }
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}
```

It would seem the problem is further down the line, either in Protagonist or Plutonium. Since it would seem that [JSON.stringify converts `Infinity` to `null`](http://stackoverflow.com/questions/16644597/json-stringify-converting-infinity-to-null) which I know is done in Plutonium.

**Comment by Baggz** [comment] 2016-03-21 20:55
Ah, thanks, @kylef!

I'll try to update my version of Protagonist.

**Comment by pksunkara** [comment] 2016-04-07 14:20
I don't think we should consider `Infinity` as a number. It is not a valid MSON number for now. I don't know how the parser is even supporting it. I haven't written the logic for it AFAIK.

**Comment by tjanc** [comment] 2018-09-03 17:07
Neither infinity nor the string `Infinity` is a number. For now, the ECMA-404 (JSON) definition is used:

> A number is a sequence of decimal digits with no superfluous
> leading zero. It may have a preceding minus sign (U+002D).
> It may have a fractional part prefixed by a decimal point (U+002E).
> It may have an exponent, prefixed by e (U+0065) or E (U+0045) and
> optionally + (U+002B) or – (U+002D) . The digits are the code points
> U+0030 through U+0039.

Which effectively means _finite precision floating point decimals_, correct me if I'm wrong.
The MSON specification is admittedly arbitrary in this regard and we have to improve on it: https://github.com/apiaryio/mson/issues/93 .

Closing as a non-issue.

**Closed by tjanc** 2018-09-03 17:07 UTC
Labels: mson
