### ISSUE TITLE
Drafter has problems with parsing nested lists indented by two spaces instead of four

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/drafter#299] opened 2016-04-14 14:29 UTC
**UPDATE:** Please see https://github.com/apiaryio/drafter/issues/299#issuecomment-209977004

-------------

Maybe my markup is incorrect, but I'm trying to write a blueprint leveraging the `+ Members` part of the `+ Parameters` section as specified [here](https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#description-13) and I couldn't come up with anything which would work. E.g. following blueprint treats `Members` as just another parameter:

```apib
FORMAT: 1A
# Beehive API
## Honey [/honey{?beekeeper}]
+ Parameters
  + beekeeper (enum[string])
    + Members
      + `Adam`
      + `Honza`
### Remove [DELETE]
+ Request
+ Response 200
```

Output:

```
warning: (8)  parameter 'Members' not specified in 'Honey' its '/honey{?beekeeper}' URI template :55:87
```

JSON:

```json
...
{
  "element": "resource",
  "meta": {
    "title": "Honey"
  },
  "attributes": {
    "href": "/honey{?beekeeper}",
    "hrefVariables": {
      "element": "hrefVariables",
      "content": [
        {
          "element": "member",
          "content": {
            "key": {
              "element": "string",
              "content": "beekeeper"
            },
            "value": {
              "element": "string",
              "content": ""
            }
          }
        },
        {
          "element": "member",
          "meta": {
            "description": "+ `Adam`\n\n+ `Honza`\n"
          },
          "content": {
            "key": {
              "element": "string",
              "content": "Members"
            },
            "value": {
              "element": "string",
              "content": ""
            }
          }
        }
      ]
    }
  },
  "content": [
    {
      "element": "transition",
      "meta": {
        "title": "Remove"
      },
      "content": [
        {
          "element": "httpTransaction",
          "content": [
            {
              "element": "httpRequest",
              "attributes": {
                "method": "DELETE",
                "title": ""
              },
              "content": []
            },
            {
              "element": "httpResponse",
              "attributes": {
                "statusCode": "200"
              },
              "content": []
            }
          ]
        }
      ]
    }
  ]
}
...
```

Also MSON tricks like following don't work, but that might be a known issue:

```apib
+ Parameters
  + beekeeper: Honza, Adam (enum[string])
```

**Comment by honzajavorek** [comment] 2016-04-14 14:38
The old syntax also doesn't work:

```apib
FORMAT: 1A
# Beehive API
## Honey [/honey{?beekeeper}]
+ Parameters
  + beekeeper ... Beekeeper to remove the honey.
    + Values
      + `Adam`
      + `Honza`
### Remove [DELETE]
+ Request (application/json)
+ Response 200
```

Produces:

```json
...
{
  "element": "resource",
  "meta": {
    "title": "Honey"
  },
  "attributes": {
    "href": "/honey{?beekeeper}",
    "hrefVariables": {
      "element": "hrefVariables",
      "content": [
        {
          "element": "member",
          "meta": {
            "description": "Beekeeper to remove the honey."
          },
          "content": {
            "key": {
              "element": "string",
              "content": "beekeeper"
            },
            "value": {
              "element": "string",
              "content": ""
            }
          }
        },
        {
          "element": "member",
          "meta": {
            "description": "+ `Adam`\n\n+ `Honza`\n"
          },
          "content": {
            "key": {
              "element": "string",
              "content": "Values"
            },
            "value": {
              "element": "string",
              "content": ""
            }
          }
        }
      ]
    }
  },
  "content": [
    ...
  ]
}
...
```

**Comment by honzajavorek** [comment] 2016-04-14 14:41
OK, my bad, it was all due to the indentation. I have used two spaces and blueprint probably strictly requires four spaces :grimacing: Following blueprint works correctly:

```apib
FORMAT: 1A
# Beehive API
## Honey [/honey{?beekeeper}]
+ Parameters
    + beekeeper ... Beekeeper to remove the honey.
        + Values
            + `Adam`
            + `Honza`
### Remove [DELETE]
+ Request (application/json)
+ Response 200
```

However, I didn't find anything relevant in the specification on how many spaces indentation of my lists **MUST** contain, so I consider this to still be a bug, either in implementation, or documentation.

**Comment by pksunkara** [comment] 2016-04-14 15:05
@honzajavorek It's a bug with our Markdown Parser. Nested Lists with spaces not 4 won't work properly.

Closing this since it is a duplicate of https://github.com/apiaryio/sundown/issues/10

**Closed by pksunkara** 2016-04-14 15:05 UTC

**Comment by honzajavorek** [comment] 2016-04-15 07:27
@pksunkara Thanks. Then I think we should mention this in Drafter readme as a known limitation.
