### ISSUE TITLE
drafter v2.3.0-pre.2 --format json --type ast does not output valid JSON

### ISSUE THREAD

**Issue by peterhellberg** [apiaryio/drafter#285] opened 2016-04-08 09:00 UTC
The output from calling `cat blueprint.md | drafter --format json --type ast` isn’t valid JSON, since the JSON document is followed by warnings along these lines:

(I’m aware of the fact that I can just fix the contents of the blueprint, but it still outputs the trailing `OK.`)

```
OK.
warning: (8)  parameter 'id' not specified in 'Update' its '/update' URI template :248:109
warning: (10)  message-body asset is expected to be a pre-formatted code block, separate it by a newline and indent every of its line by 8 spaces or 2 tabs :369:47;418:34
warning: (10)  message-body asset is expected to be a pre-formatted code block, separate it by a newline and indent every of its line by 8 spaces or 2 tabs :455:13;470:43
warning: (8)  parameter 'duration' not specified in 'Sync' its '/sync' URI template :612:161
warning: (10)  message-body asset is expected to be a pre-formatted code block, separate it by a newline and indent every of its line by 8 spaces or 2 tabs :785:47;834:34
warning: (10)  message-body asset is expected to be a pre-formatted code block, separate it by a newline and indent every of its line by 8 spaces or 2 tabs :871:13;886:43
```

Is this the expected behavior? If so, why?

**Comment by klokane** [comment] 2016-04-08 09:14
Can you, please, provide source blueprint?

**Comment by w-vi** [comment] 2016-04-08 09:22
JSON goes to `stdout` and these things go to `stderr` so if you do `cat blueprint.md | drafter --format json --type ast 2>/dev/null` you should get just the JSON data.

**Comment by pksunkara** [comment] 2016-04-08 09:46
This is the expected behaviour which we have been following since a long time. Not something which was introduced in recent releases. I think @w-vi explained it satisfactorily, so I am closing this.

**Closed by pksunkara** 2016-04-08 09:46 UTC

**Comment by kylef** [comment] 2016-04-08 09:54
To clarify, when you use `|` it will only pipe the stdout by default, so the `OK.` will not be handled to other process. Using `2>/dev/null` isn't necessary when piping or forwarding stdout to other processes.

```shell
$ drafter foo.apib -f json -t ast | json -a ast.name

OK.
Hello World API
```

```shell
$ drafter foo.apib -f json -t ast 
{
  "_version": "2.2",
  "ast": {
    "_version": "4.0",
    "metadata": [],
    "name": "Hello World API",
    "description": "",
    "element": "category",
    "resourceGroups": [],
    "content": []
  },
  "error": {
    "code": 0,
    "message": "",
    "location": []
  },
  "warnings": []
}

OK.
```

Where `OKAY.` is printed directly from stderr, and the JSON body is passed to `json` from stdout. `json` tool then outputs the name of my API "Hello World API".

**Comment by peterhellberg** [comment] 2016-04-08 10:38
Thank you for the clarification about `stderr`.
