### ISSUE TITLE
"warning: (4)  no property name" if MSON consists of many nested objects

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/drafter#252] opened 2016-03-22 11:30 UTC
While trying to resolve https://github.com/apiaryio/dredd/issues/424 I found following issue in Drafter:

```apib
FORMAT: 1A

# Hotels API

# Group Hotels

## Hotels [/hotels]

### Get Hotel [GET]

+ Response 200 (application/json)

    + Attributes
        - property
            - property
                - property
                    - property
                        - property
                            - property
                                - property
                                    - property
                                        - property: value
```

...produces

```
element: "parseResult"
content:
  -
    element: "annotation"
    meta:
      classes:
        - "warning"
    attributes:
      code: 4
      sourceMap:
        -
          element: "sourceMap"
          content: []
    content: "no property name"

OK.
warning: (4)  no property name
```

Even if Drafter does work with limit on how much nesting is supported, in my opinion this is a bug, because:

- The original API Blueprint document came from a real world situation. Nine levels of nesting doesn't seem too much to me and as we can see in https://github.com/apiaryio/dredd/issues/424, it's perfectly possible someone can meet the limit even without trying to find the boundaries by writing artificial blueprints.
- The message given by Drafter doesn't make sense and doesn't refer to any limit. Moreover, it is warning, so subsequent tooling doesn't treat the situation as a failure. But it obviously is a failure to parse the blueprint.
- Documentation of Drafter doesn't states any limits.

**Comment by kylef** [comment] 2016-03-22 19:16
The underlying markdown parser has a limit on maximum nesting, which is currently at 32, which allows up to 11th nested level items. This isn't a limitation in Drafter, but the underlying markdown parser (sundown).

We've already increased it from 16 to 32 (from https://github.com/apiaryio/markdown-parser/pull/13) to buy us "more time".

There is a tracking issue on our sundown fork (https://github.com/apiaryio/sundown/issues/11).

Ideally we can remove this limitation in the future, for now I would advise the user to break down their blueprint into separate data structures.

**Comment by kylef** [comment] 2016-03-22 19:18
I'd expect this error isn't directly about the maximum nesting, but because of data was "lost" during the markdown parsing due to the maximum nesting there is a different surfaced error.

**Comment by honzajavorek** [comment] 2016-03-22 22:39
> I'd expect this error isn't directly about the maximum nesting, but because of data was "lost" during the markdown parsing due to the maximum nesting there is a different surfaced error.

Thanks, now the message makes more sense. I'll advise user about breaking up the attributes into separate pieces.

**Comment by kylef** [comment] 2016-03-31 12:29
Linking together this as dupe of https://github.com/apiaryio/snowcrash/issues/362 and potentially related to https://github.com/apiaryio/drafter/issues/254.

**Comment by pksunkara** [comment] 2016-04-05 14:48
This is fixed now.

**Closed by pksunkara** 2016-04-05 14:48 UTC
Labels: bug
