### ISSUE TITLE
New style parameter breaking when using backtick

### ISSUE THREAD

**Issue by earnaway** [apiaryio/drafter#123] opened 2015-09-25 11:06 UTC
I originally posted this in the aglio repo, but apparently it's caused by the drafter code, not the aglio, so thought I'd ask in here if drafter was where the bug was. Thanks.

I've noticed an issue when there are underscores as part of the params in the resources.

Here's an example:

```
FORMAT: 1A

# Test Doc

# Group Tests

# Test endpoint [/test{?status,order_by,sort,page,per_page}]

+ Parameters
    + status: paid (optional, string) - some test status
    + order_by: transaction_date (optional, enum) - one of transaction_date, merchant_network_name, amount, user_commission, status
    + sort: asc (optional, enum) - one of asc, desc
    + page: 1 (optional, integer) - pagination parameter
    + per_page: 5 (optional, integer) - pagination parameter

### Fetch some data [GET]

+ Response 204
```

When running aglio against the above with the following command
`"./node_modules/aglio/bin/aglio.js --theme-style default -i test.apib -o test.html"`
then I get the following warning:

```
>> Line 9: parameter 'order_by: transaction_date' not specified in 'Test endpoint' its '/test{?status,order_by,sort,page,per_page}' URI template (warning code 8)
```

And the generated html looks like:

![screen shot 2015-09-25 at 12 01 13 copy](https://cloud.githubusercontent.com/assets/12640813/10098955/53b9b2a0-637d-11e5-8124-bbedfa18fe7b.jpg)

I've noticed if I remove all the underscores in the examples, it works as expected, so must be an issue with the way it handles underscores in the parameters.

My aglio version is:
`aglio 2.0.4`
`olio 1.2.1`

**Comment by earnaway** [comment] 2015-09-25 11:12
To follow up from the above, if I run the command:
`./drafter/bin/drafter test.apib` on the above .apib file, the JSON returns the following (only showing the relevant issue):

```
{
  "name": "order_by: transaction_date",
  "description": "one of transaction_date, merchant_network_name, amount, user_commission, status",
  "type": "enum",
  "required": false,
  "default": "",
  "example": "",
  "values": []
},
```

with a warning:

```
"warnings": [
  {
    "code": 8,
    "message": "parameter 'order_by: transaction_date' not specified in 'Test endpoint' its '/test{?status,order_by,sort,page,per_page}' URI template",
    "location": [
      {
        "index": 101,
        "length": 373
      }
    ]
  }
],
```

The "name" should be "order_by" without the ": transaction_date". If I remove all the underscores it works as expected.

**Comment by pksunkara** [comment] 2015-09-25 11:59
`_` is a special character in MSON. So, please enclose `order_by` within `` ` ``. `` `order_by` ``

**Comment by earnaway** [comment] 2015-09-25 13:13
When trying it with the following changes:

```
+ Parameters
    + status: paid (optional, string) - some test status
    + `order_by`: transaction_date (optional, enum) - one of transaction_date, merchant_network_name, amount, user_commission, status
    + sort: asc (optional, enum) - one of asc, desc
```

I get the following warning:

```
"warnings": [
    {
      "code": 5,
      "message": "ignoring unrecognized block",
      "location": [
        {
          "index": 175,
          "length": 130
        }
      ]
    }
  ],
```

**Comment by pksunkara** [comment] 2015-09-25 13:14
Can you please give us the complete blueprint?

**Comment by earnaway** [comment] 2015-09-25 13:33
I'm testing the underscores, and using this blueprint:

```
FORMAT: 1A

# Test Doc

# Group Tests

# Test endpoint [/test{?status,order_by,sort,page,per_page}]

+ Parameters
    + status: paid (optional, string) - some test status
    + `order_by`: transaction_date (optional, enum) - one of transaction_date, merchant_network_name, amount, user_commission, status
    + sort: asc (optional, enum) - one of asc, desc
    + page: 1 (optional, integer) - pagination parameter
    + per_page: 5 (optional, integer) - pagination parameter

### Fetch some data [GET]

+ Response 204
```

which results in an output with warnings here:
https://gist.github.com/earnaway/acc2e37b4c266411fe55

My command:
`./node_modules/drafter/bin/drafter test.apib`

**Comment by earnaway** [comment] 2015-09-25 15:20
Hi, just wondering if you could replicate that above using that blueprint I provided?

**Comment by pksunkara** [comment] 2015-09-28 02:32
@earnaway Looks like this is a bug on our side. The `` ` `` are affecting the new style parameter recognition somehow.

**Comment by earnaway** [comment] 2015-10-01 12:19
Any idea if this is on the radar to update and fix fairly soon? Or just a rough ETA on it if you have an idea? Thanks.

**Comment by earnaway** [comment] 2015-10-15 11:57
Hi @pksunkara - just wondering if there was any recent update to this with the ``` ` ``` issue? Thanks!

**Comment by kylef** [comment] 2015-10-15 19:16
Hi @earnaway, we don't have any updates yet. But this is on our radar, we have some [a couple of regression issues which we need to tackle first](https://github.com/apiaryio/drafter/milestones/1.1.0) before getting to this one. We'll be sure to update this issue when we get to working on this.

**Comment by earnaway** [comment] 2015-10-19 13:28
Thanks @kylef

**Comment by Clar64** [comment] 2015-11-18 09:18
Any time estimate on this?

**Comment by pksunkara** [comment] 2015-11-20 14:38
@Clar64 Unfortunately, we are currently working very hard on getting MSON and Attributes out. Once that is done, this bug is very high on our priority list and we would love to fix this as soon as possible.

**Comment by Clar64** [comment] 2015-11-20 15:38
Thanks, we appreciate it!

**Comment by truebit** [comment] 2016-01-22 13:42
Any update on this? This issue is too annoying to make other guys in the team believing in api-blueprint...

**Comment by bennettellis** [comment] 2016-02-12 17:40
ditto

**Comment by pksunkara** [comment] 2016-02-12 20:14
This has now been fixed in parser master branch. We will be incorporating it in Apiary soon.

**Comment by bennettellis** [comment] 2016-02-12 20:40
Awesome.  Thank you!!

**Comment by earnaway** [comment] 2016-02-14 17:43
Excellent! Thank you :+1:

**Comment by truebit** [comment] 2016-02-25 10:32
Any update?

**Comment by pksunkara** [comment] 2016-02-25 10:41
Unfortunately, this is not yet deployed. We will update you as soon as it is.

**Comment by kylef** [comment] 2016-03-18 14:28
This bug was resolved in [Drafter 2.3.0-pre.0](https://github.com/apiaryio/drafter/releases/tag/v2.3.0-pre.0), and it has been rolled out to Apiary providing you are behind the [Attributes Kit feature flag](https://github.com/apiaryio/api-blueprint/issues/191#issuecomment-178044764).

**Closed** 2016-04-04 15:51 UTC
Labels: bug

**Comment by earnaway** [comment] 2017-01-06 11:45
What would be the best/easiest way to install `Drafter 2.3.0-pre.0` - I'm only on drafter 1.2.0 but would like to try get `2.3.0-pre.0`.
Thanks

**Comment by pksunkara** [comment] 2017-01-06 12:45
@earnaway You can use homebrew to install the latest drafter 3.2.x. The command is follows:

```
brew install --HEAD https://raw.github.com/apiaryio/drafter/master/tools/homebrew/drafter.rb
```

**Comment by kamihouse** [comment] 2018-09-28 17:14
Guys we can do this:

```apib
+ Parameters
     + `grant_type`: `refresh_token` (string, required) - Tipo de concessão
```

Works great!
