### ISSUE TITLE
Mixins doesn't produce correct assets for resource attributes

### ISSUE THREAD

**Issue by honzajavorek** [apiaryio/drafter#248] opened 2016-03-08 15:42 UTC
https://github.com/apiaryio/drafter/issues/223 is not fully fixed yet. Please see [this Dredd build](https://travis-ci.org/apiaryio/dredd/jobs/111707928) and my report in https://github.com/apiaryio/dredd/issues/354#issuecomment-188705444. I'm sorry if I missed a Drafter issue where this would be already tracked.

**Comment by klokane** [comment] 2016-03-08 15:57
@hj can you please provide minimal blueprint with and attach expected output?

**Comment by klokane** [comment] 2016-03-08 16:58
I tested it with example on top of report apiaryio/dredd#354

```
FORMAT: 1A                                                                                         

# API
  
# Group X                                                                                          
      
## GET /
        
+ Response 200 (application/json; charset=utf-8)                                                   
        
    + Attributes (Testing)                                                                         
          
# Data Structures
        
## Testing (object)                                                                                
+ message: Hello Word! (string)                                                                    
+ Include Level Two                                                                                
          
## Level Two (object)
+ myobject (object) 
  + item (string)
```

On master seem to be working correctly, generated schema:
```
{                                                                                                  
  "$schema": "http://json-schema.org/draft-04/schema#",                                            
  "type": "object",                                                                                
  "properties": {                                                                                  
    "message": {                                                                                   
      "type": "string"                                                                             
    },                                                                                             
    "myobject": {                                                                                  
      "type": "object",                                                                            
      "properties": {                                                                              
        "item": {                                                                                  
          "type": "string"                                                                         
        }                                                                                          
      }                                                                                            
    }                                                                                              
  }                                                                                                
}
```
 or did I miss something?

@honzajavorek Are you sure you you have build dredd against master?

**Comment by honzajavorek** [comment] 2016-03-08 19:09
The test is on top of latest Drafter version published on npm. So you say
this is fixed, but not released yet? I'll verify everything tomorrow, what
I wrote in this comment is just from top of my head.

**Comment by honzajavorek** [comment] 2016-03-08 19:10
Sorry, I meant Protagonist version on npm.

**Comment by klokane** [comment] 2016-03-08 21:18
Not sure about latest version of protagonist, will try to check on tomorow morning

**Comment by honzajavorek** [comment] 2016-03-09 17:02
The latest released protagonist is 1.2.6. It seems it uses 2.2.0 Drafter. According to https://github.com/apiaryio/drafter/releases/tag/v2.3.0-pre.0 the fix was released in the v2.3.0-pre version.

You are right that it's (probably?) fixed in Drafter, but I can't verify that since Protagonist is behind. However, that's Protagonist issue now, not Drafter issue. Moving this to https://github.com/apiaryio/protagonist/issues/133.

**Comment by honzajavorek** [comment] 2016-03-10 08:24
I updated my https://github.com/apiaryio/dredd/pull/380 to depend on `v1.3.0-pre.0`, but results of tests didn't change at all. Please see the PR - I've updated the description to contain an overview table of what's broken and what works correctly.

**Comment by klokane** [comment] 2016-03-10 08:29
@honzajavorek can you, please, provide minimal blueprint where is reported bug reproducable and related output.

**Comment by honzajavorek** [comment] 2016-03-10 09:43
@klokane I tried to build a minimal app with minimal blueprint for each test case. Please see https://github.com/apiaryio/protagonist-include-issue and let me know if anything is unclear, but I think I'd be struggling to make this even more minimal. You can run tests by `npm test`. The `index.js` is full of comments on what I pass in and what expect. There's also Travis CI integration to prove that the tests are failing.

When building this, I came to a conclusion that this is actually very closely related to https://github.com/apiaryio/drafter/issues/243 and it's possibly a duplicate of that issue.

**Comment by klokane** [comment] 2016-03-10 10:11
@honzajavorek 

I've tried to reproduce it with minimal blueprint reduced from your `resource-array.apib` into:
```
## GET /  
      
+ Response 200 (application/json)                                                                  
    + Attributes
        + id
        + Include DimensionsMixin                                                                  
                                                                                                   
## Data Structures
      
### DimensionsMixin (object)                                                                       
+ dimensions (array)                                                                               
    + 20, 30, 40 (array[number])
```

It seem that you are right, there is generated schema:
```
{                                                                                                  
  "$schema": "http://json-schema.org/draft-04/schema#",                                            
  "type": "object",                                                                                
  "properties": {                                                                                  
    "id": {                                                                                        
      "type": "string"                                                                             
    }                                                                                              
  }                                                                                                
}
```

Mixin part in asset is missing (Both JSON and Schema too).

We will look at this bug, but I would like to please you next time try to reduce your blueprint to really __minimal__ use case as possible, like one above.

**Comment by klokane** [comment] 2016-03-10 10:21
Hmm this is interesting. 
```
## GET / 

+ Response 200 (application/json)
    + Attributes (array)
        + Include DimensionsMixin


## Data Structures

### DimensionsMixin (array)
- a (object)
    - k: v
```

If you force `Attributes` to array type, it seems JSON is correct while Schema is wrong
```json
[                                                                                                  
  {                                                                                                
    "k": "v"                                                                                       
  }                                                                                                
]    
```

```json+schema
{                                                                                                  
  "$schema": "http://json-schema.org/draft-04/schema#",                                            
  "type": "array"                                                                                  
}
```

**Comment by honzajavorek** [comment] 2016-03-10 11:08
@klokane I'm sorry for not providing example, which would be minimal enough.

Could you please guide me on how can I easily achieve using Drafter with blueprint and having JSON & JSON Schema on output? I get AST or Refract, which are hard to read, with JSON & JSON Schema assets serialized into string, which are even harder to read. For me it's easier to assemble working test than to manually unserialize the results from parse result in console. I'd be interested in how do you work with this to improve my workflow.

Thanks for looking at this bug!

**Comment by honzajavorek** [comment] 2016-03-10 11:10
Ah! I get it - you meant **minimal blueprint**. I should have cut down any extraneous content in the blueprint not necessary to reproduce the bug. Please ignore my comment above, I'm sorry for not getting you right at first.

**Comment by klokane** [comment] 2016-03-10 11:17
No problem.
At final we got in :)

About schema/json - currently it is no possible. 
I do it by 
- read output of command in __vim__, 
- delete everything in output except line with schema 
- `:%s/\\n/^M/` (replace `\n` be real newline) 
- `:%s/\\"/"/g` (replace escaped qoutes, by qoutes)

Probably i will create macro for it (because i repeat it often :)

**Comment by klokane** [comment] 2016-03-10 11:19
I thing about shell script via sed as filted which allow it

**Comment by klokane** [comment] 2016-03-10 11:30
@honzajavorek as start:
`./drafter resource-array.apib | grep "\$schema" | sed -e 's/\\n/\n/g'  -e 's/\\"/"/g' -e 's/^\s\+content: //g'`

**Comment by kylef** [comment] 2016-03-31 12:12
After deeper investigation I've found this to be a duplicate of https://github.com/apiaryio/drafter/issues/243 and going to close it.

**Closed by kylef** 2016-03-31 12:12 UTC
Labels: bug
