### ISSUE TITLE
Support of exploded variables from URI Template in URI Parameters

### ISSUE THREAD

**Issue by ajkl2533** [apiaryio/drafter#671] opened 2019-02-15 14:50 UTC
I’m currently dealing with expanding values from URI Params to the URI Template to construct actual usable URL and I did encounter one problem, I have this:
```
FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Questionaire

## Questions Collection [/questions/{id,di}/details/{type}{?page*}]

### GET
+ Parameters
    + id: 21 (number, required)
    + di: test2 (string, optional)        
        + Default: test
    + type: status/type (string, required)
    + page: 5 (number, optional)
        + Default: 1
```

And I’m getting Semantic Issue from parser:
```
parameter 'page' is not found within the URI template '/questions/{id,di}/details/{type}{?page*}' for 'Questions Collection'
``` 

Which unfortunately isn’t true because `page` is in the URI Template but it has `explode variable modifier`, is that wanted behaviour or is it bug?

According to API Blueprint specs, we are supporting `explode variable modifier` which works fine, but do not support an `array` or `object` in URI Params section, but that shouldn’t matter in this case because we can have single value in exploded variable.

**Comment by kylef** [comment] 2019-02-18 09:16
Closing as a duplicate of https://github.com/apiaryio/drafter/issues/553

**Closed by kylef** 2019-02-18 09:16 UTC
Labels: duplicate
